#!/bin/bash

# Entrypoint script for OpenSlides server component

set -e

echo "Retrieving secure admin password"
source /run/secrets/os_admin

[[ -n "${OPENSLIDES_ADMIN_PASSWORD}" ]] || {
  echo "ERROR: OpenSlides admin password not set.  Aborting."
  exit 2
}

wait-for-it --timeout=5 postgres:5432

echo 'running migrations'
python manage.py migrate

echo 'change admin password'
python manage.py insecurechangepassword admin "${OPENSLIDES_ADMIN_PASSWORD}"

echo 'executing server'
printf 'INFO: Running CMD: "%s".\n' "$*"

# Expected commands are one of:
# - daphne -b 0.0.0.0 -p 8000 openslides.asgi:application
# - gunicorn -w 4 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker \
#   openslides.asgi:application
exec $*
